name: Daily Pipeline

on:
  schedule:
    # 13:00 UTC = 8:00 ET (standard time; adjust if needed for DST)
    - cron: '0 13 * * 1-5'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migrate DB
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          python migrate.py migrate | cat
      - name: Run daily pipeline (previous business day)
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          POLYGON_S3_ACCESS_KEY: ${{ secrets.POLYGON_S3_ACCESS_KEY }}
          POLYGON_S3_SECRET_KEY: ${{ secrets.POLYGON_S3_SECRET_KEY }}
        run: |
          python daily_schedule.py --recent 1 --retention 60 | cat

