name: Daily Process

on:
  schedule:
    # 8:00 AM EST (13:00 UTC) on weekdays - day after business days
    - cron: '0 12 * * 2-6'
  workflow_dispatch: {}

jobs:
  run-daily:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      POLYGON_S3_ACCESS_KEY: ${{ secrets.POLYGON_S3_ACCESS_KEY }}
      POLYGON_S3_SECRET_KEY: ${{ secrets.POLYGON_S3_SECRET_KEY }}
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily process
        run: |
          python daily_schedule.py --recent 30 --retention 30 | cat
