name: Daily ETL Schedule

on:
  schedule:
    - cron: '10 23 * * 1-5'
  workflow_dispatch:
    inputs:
      recent:
        description: 'Recent business days to load'
        required: false
        default: '3'
      retention:
        description: 'Retention in business days'
        required: false
        default: '30'
      include_otc:
        description: 'Include OTC (true/false)'
        required: false
        default: 'false'
      force:
        description: 'Force re-scrape (true/false)'
        required: false
        default: 'false'

jobs:
  run-daily:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      RECENT_DAYS: ${{ github.event.inputs.recent || '3' }}
      RETENTION_DAYS: ${{ github.event.inputs.retention || '30' }}
      INCLUDE_OTC: ${{ github.event.inputs.include_otc || 'false' }}
      FORCE: ${{ github.event.inputs.force || 'false' }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python migrate.py migrate

      - name: Run daily schedule
        run: |
          python daily_schedule.py \
            --recent ${RECENT_DAYS} \
            --retention ${RETENTION_DAYS} \
            $([ "${INCLUDE_OTC}" = "true" ] && echo "--include-otc" || true) \
            $([ "${FORCE}" = "true" ] && echo "--force" || true)


